import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import {
  decrementKnowledge,
  getRandomUnknownData,
  incrementKnowledge,
} from "../core/data";
import { RememberData } from "../core/models";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [wordData, setWordData] = useState<RememberData>();

  function refreshData() {
    setWordData(getRandomUnknownData(0));
  }

  useEffect(refreshData, []);

  function handleClickYes() {
    if (wordData) {
      incrementKnowledge(wordData.word);
      refreshData();
    }
  }

  function handleClickNo() {
    if (wordData) {
      decrementKnowledge(wordData.word);
      refreshData();
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Remember Words</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {wordData && (
        <main className={styles.main}>
          <div className={styles.title}>
            Do you know <code className={styles.code}>{wordData!.word}</code>?
          </div>

          <div>
            <button
              className={`${styles.button} ${styles.buttonGreen}`}
              onClick={handleClickYes}
            >
              Yes
            </button>
            <button
              className={`${styles.button} ${styles.buttonRed}`}
              onClick={handleClickNo}
            >
              No
            </button>
          </div>
        </main>
      )}
    </div>
  );
};

export default Home;
